AllCops:
  Exclude:
    - 'spec/support/bookstore/**/*'
  TargetRubyVersion: 2.5
Documentation:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'configure']
Metrics/MethodLength:
  Max: 18
Metrics/LineLength:
  Max: 90
